apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: gohttpbin
build:
  artifacts:
    - image: uhziel/gohttpbin
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s.yaml
